"""Generate metric view YAML files from discovered table metadata."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from .heuristics import classify_table, suggest_aggregation
from .models import (
    ColumnRole,
    DimensionDef,
    DiscoveredTable,
    JoinDef,
    MeasureDef,
    MetricViewSpec,
)

logger = logging.getLogger(__name__)


def _humanize(col_name: str) -> str:
    """'total_order_amount' → 'Total Order Amount'"""
    return col_name.replace("_", " ").strip().title()


def _find_join_key(source: DiscoveredTable, dim: DiscoveredTable) -> str | None:
    """Auto-detect the join key between a fact table and a dimension table.

    Three-step heuristic (returns on first match):
    1. Shared column with a key suffix (_key, _id, _sk) → returns the bare column name
       for a USING clause.
    2. Derived candidate from the dimension name (e.g. dim_customer → customer_id) exists
       in both tables → returns a fully-qualified "source.col = dim.col" ON expression.
    3. No match → returns None (caller emits a '???' placeholder for the user to fill in).
    """
    source_cols = {c.name.lower() for c in source.columns}
    dim_cols = {c.name.lower() for c in dim.columns}

    key_suffixes = ("_key", "_id", "_sk")
    source_keys = {c for c in source_cols if any(c.endswith(s) for s in key_suffixes)}
    dim_keys = {c for c in dim_cols if any(c.endswith(s) for s in key_suffixes)}
    shared = source_keys & dim_keys
    if shared:
        return sorted(shared)[0]

    dim_name = dim.table_name.lower().removeprefix("dim_")
    for suffix in key_suffixes:
        candidate = f"{dim_name}{suffix}"
        if candidate in source_cols:
            for dc in dim_cols:
                if dc.endswith(suffix):
                    return f"source.{candidate} = {dim.table_name}.{dc}"
    return None


def spec_from_tables(
    source: DiscoveredTable,
    dim_tables: list[DiscoveredTable] | None = None,
) -> MetricViewSpec:
    """Generate a MetricViewSpec from a fact table + optional dimension tables."""
    classified_source = classify_table(source.columns)

    dimensions: list[DimensionDef] = []
    measures: list[MeasureDef] = []
    joins: list[JoinDef] = []

    for col in classified_source:
        if col.role == ColumnRole.DIMENSION:
            dimensions.append(
                DimensionDef(
                    name=_humanize(col.name),
                    expr=col.name,
                    comment=col.comment,
                )
            )
        elif col.role == ColumnRole.MEASURE:
            measures.append(
                MeasureDef(
                    name=_humanize(col.name),
                    expr=suggest_aggregation(col.name, col.type_name),
                    comment=col.comment,
                )
            )

    measures.insert(
        0,
        MeasureDef(
            name="Row Count",
            expr="COUNT(1)",
            comment="Total number of records",
        ),
    )

    for dim in dim_tables or []:
        join_key = _find_join_key(source, dim)

        join_def_kwargs: dict[str, Any] = {"name": dim.table_name, "source": dim.fqn}
        if join_key and "=" in join_key:
            join_def_kwargs["on"] = join_key
        elif join_key:
            join_def_kwargs["using"] = [join_key]
        else:
            join_def_kwargs["on"] = f"source.??? = {dim.table_name}.???"

        joins.append(JoinDef(**join_def_kwargs))

        classified_dim = classify_table(dim.columns)
        for col in classified_dim:
            if col.role == ColumnRole.IGNORE:
                continue
            if col.name.lower().endswith(("_key", "_id", "_sk")):
                continue
            dimensions.append(
                DimensionDef(
                    name=_humanize(col.name),
                    expr=f"{dim.table_name}.{col.name}",
                    comment=col.comment,
                )
            )

    return MetricViewSpec(
        source=source.fqn,
        comment=source.comment or f"Metric view for {source.table_name}",
        joins=joins if joins else None,
        dimensions=dimensions,
        measures=measures,
    )


def spec_to_yaml(spec: MetricViewSpec) -> str:
    """Serialize MetricViewSpec to YAML string. Manual formatting — not yaml.dump().

    NOTE: Does not render materialization or window specs. These are hand-authored
    by the user directly in YAML — they are never generated by spec_from_tables().
    """
    lines = [f'version: "{spec.version}"']

    if spec.comment:
        lines.append(f'comment: "{spec.comment}"')

    lines.append(f"source: {spec.source}")

    if spec.filter:
        lines.append(f'filter: "{spec.filter}"')

    if spec.joins:
        lines.append("joins:")
        for j in spec.joins:
            _render_join(lines, j, indent=2)

    lines.append("dimensions:")
    for d in spec.dimensions:
        lines.append(f"  - name: {d.name}")
        lines.append(f'    expr: "{d.expr}"')
        if d.comment:
            lines.append(f'    comment: "{d.comment}"')

    lines.append("measures:")
    for m in spec.measures:
        lines.append(f"  - name: {m.name}")
        lines.append(f'    expr: "{m.expr}"')
        if m.comment:
            lines.append(f'    comment: "{m.comment}"')

    return "\n".join(lines) + "\n"


def _render_join(lines: list[str], join: JoinDef, indent: int) -> None:
    """Render a join block to YAML lines, recursing into nested joins.

    Each level of nesting adds 4 spaces to `indent` so children are indented
    relative to their parent's `joins:` key.
    """
    pad = " " * indent
    lines.append(f"{pad}- name: {join.name}")
    lines.append(f"{pad}  source: {join.source}")
    if join.on:
        lines.append(f'{pad}  "on": {join.on}')
    if join.using:
        lines.append(f"{pad}  using:")
        lines.extend(f"{pad}    - {u}" for u in join.using)
    if join.joins:
        lines.append(f"{pad}  joins:")
        for child in join.joins:
            _render_join(lines, child, indent + 4)


def write_yaml_file(
    spec: MetricViewSpec,
    output_path: str | Path,
    overwrite: bool = False,
) -> Path | None:
    """Write YAML file. Returns path if written, None if skipped."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not overwrite:
        logger.info(f"Skipping {path} (already exists, use --overwrite)")
        return None

    yaml_content = spec_to_yaml(spec)
    path.write_text(yaml_content)
    logger.info(f"Generated {path}")
    return path
